export const REQUEST_MSI_PROPERTIES = 'REQUEST_MSI_PROPERTIES'
export const SUCCESS_FETCH_MSI_PROPERTIES = 'SUCCESS_FETCH_MSI_PROPERTIES'
export const ERROR_FETCH_MSI_PROPERTIES = 'ERROR_FETCH_MSI_PROPERTIES'